language: python
python:
  - "3.7"
  - "3.8"
services:
  - docker
#install dependencies
install:
  - sudo apt-get -y install wget
  - pip3 install -r requirements.txt
#command to run the testing
script:
  - scripts/pipeline_test.py
