language: python
python:
  - "3.7"
  - "3.8"
services:
  - docker
#install dependencies
install:
  - sudo apt-get install -y libxml-libxml-perl
  - pip install -r requirements.txt
#command to run the testing
script:
  - travis_wait 30 scripts/pipeline_test.py
